<?php

namespace Database\Seeders;

use App\Models\Evento;
use Illuminate\Database\Seeder;

class EventoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $eventos = [
            'Paquete recibido del cliente.',
            'Paquete en camino a ubicacion nacional.',
            'Paquete recibido en oficina origen de transito.',
            'Paquete enviado a aduana.',
            'Paquete recibido en centro de procesamiento.',
            'Paquete retenido en aduana.',
            'Paquete en devolucion desde la aduana.',
            'Paquete incluido en la saca de envio.',
            'Paquete eliminado del la saca de envio.',
            'Detalles del paquete registrados.',
            'Detalles del paquete registrados en oficina de transito.',
            'Paquete enviado al extranjero.',
            'Paquete incluido en la saca nacional.',
            'Paquete eliminado de la saca nacional.',
            'Exportacion del paquete cancelada.',
            'Paquete recibido en oficina destino de transito.',
            'Paquete en camino a aduana.',
            'Paquete recibido en oficina de entrega(Listo para entregar).',
            'Paquete recibido en ubicacion especifica.',
            'Informacion de aduana del paquete registrada.',
            'Intento fallido de entrega del paquete.',
            'Paquete entregado exitosamente.',
            'Paquete en devolucion desde aduana.',
            'Paquete transferido al agente de entrega.',
            'Paquete recibido desde el extranjero.',
            'Informacion del destinatario del paquete registrada.',
            'Paquete recibido en oficina de transito internacional.',
            'Paquete recibido en oficina de transito nacional.',
            'Paquete recibido automaticamente en oficina de transito.',
            'Paquete creado automaticamente.',
            'Paquete actualizado',
            'Correccion de datos del paquete',
            'Saca registrado en ubicacion.',
            'Saca enviado a aduana para revision.',
            'Saca recibido en ubicacion.',
            'Saca transferido al agente de entrega.',
            'Paquete recibido automaticamente: pendiente de digitalizacion.',
            'Paquete retenido en oficina de transitos.',
            'Paquete retenido en oficina de transito.',
            'Paquete recibido en centro de clasificacion.',
            'Paquete procesado en centro de clasificacion.',
            'Paquete retenido en punto de entrega.',
            'Paquete en camino para entrega fisica.',
            'Paquete recibido en punto de recogida.',
            'Importacion del paquete detenida.',
            'Paquete incluido en una saca externo.',
            'Paquete recogido por el cliente.',
            'Paquete eliminado del contenedor externo.',
            'Retorno del paquete al remitente detenido.',
            'Contenedor del paquete creado.',
            'Contenedor del paquete cerrado.',
            'Contenedor del paquete reabierto.',
            'Contenedor del paquete enviado a ubicacion nacional.',
            'Contenedor del paquete recibido desde oficina postal.',
            'Transporte del contenedor del paquete modificado.',
            'Contenedor del paquete enviado al extranjero.',
            'Contenedor del paquete enviado al extranjero (confirmado electronicamente).',
            'Contenedor del paquete recibido desde el extranjero.',
            'Contenedor del paquete abierto en destino.',
            'Contenedor del paquete recibido en ubicacion nacional.',
            'Digitalizacion del contenedor del paquete incompleta.',
            'Digitalizacion del contenedor del paquete finalizada.',
            'Contenedor del paquete marcado como eliminado.',
            'Contenedor del paquete gestionado por transportista.',
            'Contenedor del paquete actualizado (salida).',
            'Contenedor del paquete actualizado (entrada).',
            'Correccion de datos del contenedor del paquete (salida).',
            'Correccion de datos del contenedor del paquete (entrada).',
            'Correccion de datos del contenedor (entrada).',
            'Manifiesto del contenedor recibido.',
            'Manifiesto del contenedor enviado.',
            'Solicitud RESDIT aceptada.',
            'Contenedor cambiado.',
            'Cambio en embarque nacional.',
            'Contenedor evaluado para muestreo.',
            'Contenedor recibido desde trasbordo directo extranjero.',
            'Marcado como transportado fuera de embarque.',
            'Contenedor pesado en bascula.',
            'Contenedor seleccionado para muestreo.',
            'Inspeccion por rayos X realizada.',
            'Despacho creado (salida).',
            'Despacho cerrado (salida).',
            'Despacho reabierto (salida).',
            'Cambio en embarque del despacho (salida).',
            'Despacho enviado al extranjero (confirmado electronicamente).',
            'Despacho recibido desde el extranjero.',
            'Despacho marcado como eliminado.',
            'Despacho actualizado (salida).',
            'Despacho actualizado (entrada).',
            'Embarque creado (salida).',
            'Embarque cerrado (salida).',
            'Embarque reabierto (salida).',
            'Embarque enviado al extranjero (confirmado electronicamente).',
            'Embarque recibido desde el extranjero.',
            'Embarque gestionado por transportista.',
            'Embarque actualizado (salida).',
            'Embarque marcado como eliminado.',
            'Embarque actualizado (entrada).',
            'Saca interna creada (salida).',
            'Saca interna cerrada (salida).',
            'Saca interna anadida al contenedor (salida).',
            'Saca interna eliminada del contenedor (salida).',
            'Saca interna reabierta (salida).',
            'Saca interna recibida (entrada).',
            'Saca interna abierta (entrada).',
            'Saca interna marcada como eliminada.',
            'BV propio creado.',
            'BV enviado al corresponsal.',
            'BV aceptado por corresponsal.',
            'BV anotado por corresponsal recibido.',
            'BV propio actualizado.',
            'BV recibido del corresponsal.',
            'BV aceptado.',
            'BV anotado.',
            'BV recibido actualizado.',
            'BV electronico aceptado.',
            'Datos importados desde XML.',
            'BV marcado como eliminado.',
            'Saca nacional creado.',
            'Saca nacional cerrado.',
            'Saca nacional reabierto.',
            'Saca nacional enviado a ubicacion.',
            'Saca nacional recibido en ubicacion.',
            'Saca nacional marcado como eliminado.',
            'Expedicion nacional creado.',
            'Expedicion nacional cerrado.',
            'Expedicion nacional reabierto.',
            'Expedicion nacional marcado como eliminado.',
            'Paquete: datos recibidos por EDI.',
            'Saca creada o actualizada.',
            'Saca recibida.',
            'Saca abierta.',
            'Paquete: datos digitalizados para transporte.',
            'Paquete: creado o actualizado automaticamente desde proceso de salida.',
            'Paquete: creado o actualizado desde especificacion de documento.',
            'Modificado segun BV.',
            'Paquete: marcado como eliminado.',
            'Paquete: documento oficial registrado.',
            'Paquete: modificado administrativamente segun documento.',
            'Paquete: creado o actualizado automaticamente desde PREDES.',
            'Paquete: creado automaticamente desde estimacion.',
            'Paquete: modificado administrativamente por BV.',
            'Paquete: registro no formado.',
            'Paquete: documento validado.',
            'Paquete: documento invalidado.',
            'Paquete: identificador modificado.',
            'PREDES no validado creado automaticamente.',
            'Declaracion creada.',
            'Declaracion enviada.',
            'Declaracion reconocida.',
            'Paquete: pago recibido.',
            'Declaracion marcada como eliminada.',
            'Declaracion actualizada.',
        ];

        $eventosUnicos = collect($eventos)
            ->map(fn (string $evento) => trim($evento))
            ->filter(fn (string $evento) => $evento !== '')
            ->unique()
            ->values()
            ->all();

        foreach ($eventosUnicos as $evento) {
            Evento::firstOrCreate([
                'nombre_evento' => $evento,
            ]);
        }
    }
}
